# -*- coding: utf-8 -*-
"""bio1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jXEH_NPSW80UREPJxWaVxqp2A9LRg7Aw
"""

!pip install biopython

dna="ATGCGCTGACGTAGC"
rna=dna.replace("T","U")
print("rna_ seq:",rna)

dna="ATGCGCGTATGC"
gc=(dna.count("G")+ dna.count("C"))/len(dna)*100
print(gc)

from google.colab import files
uploaded =files.upload()

from Bio import SeqIO
seq="ATGCGTGCGTA"
for seq in SeqIO.parse("gene.fna","fasta"):
  print(seq.id)
  print(seq.seq)



from Bio.Seq import Seq
dna=Seq("ATGCGCTGCGCGTATGCG")
rna=dna.transcribe()
print("rna is :",rna)

from Bio.Seq import Seq
dna=Seq("ATGCGCGCGATATGCGATT")
protein=dna.translate()
print("protein is :",protein)

from Bio.Seq import Seq
dna=Seq("ACGCGATGCGTTTTATGCGAT")
print(dna.reverse_complement())

from Bio.Seq import Seq
dna=Seq("ACGCGATGCGTTTTATGCGAT")
for base in "ATGC":
  print(base,"=",dna.count(base))

se1=atadhctagca
seq2-atadagstscg      0 atcgctgac
                       0Atgcgtg

[w, rt, t, y]
0

from Bio import pairwise2
seq1="ATGCGCGTGCGTGAT"
seq2="ATGCGCGTGCGTATG"
alignments=pairwise2.align.globalxx(seq1,seq2)
print(alignments[0])

from Bio import pairwise2
seq1="ATGCGCGTGCGTGAT"
seq2="ATGCGCGTGCGTATG"
alignments=pairwise2.aligner(seq1,seq2)
print(alignments[0])

local    global

match a=a
mismatch T=G          m =1 , mis =0
                      m=1 gap=0 mis=-1

gap a=_